// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    LeaguePointsLineChart: typeof import('./src/components/LeaguePointsLineChart.vue')['default']
    LeagueStandingsBarChart: typeof import('./src/components/LeagueStandingsBarChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarNav: typeof import('./src/components/SidebarNav.vue')['default']
    WeeklyStandingsLineChart: typeof import('./src/components/WeeklyStandingsLineChart.vue')['default']
  }
}
