/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    LeaguePointsLineChart: typeof import('./src/components/LeaguePointsLineChart.vue')['default']
    LeagueStandingsBarChart: typeof import('./src/components/LeagueStandingsBarChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarNav: typeof import('./src/components/SidebarNav.vue')['default']
    WeeklyStandingsLineChart: typeof import('./src/components/WeeklyStandingsLineChart.vue')['default']
  }
}
