export interface League {
    avatar: string;
    bracket_id?: null;
    company_id?: null;
    display_order: number;
    draft_id: string;
    group_id?: null;
    last_author_avatar: string;
    last_author_display_name: string;
    last_author_id: string;
    last_author_is_bot: boolean;
    last_message_attachment?: null;
    last_message_id: string;
    last_message_text_map?: null;
    last_message_time: number;
    last_pinned_message_id?: null;
    last_read_id: string;
    last_transaction_id?: number | null;
    league_id: string;
    loser_bracket_id?: null;
    metadata?: null;
    name: string;
    previous_league_id: string;
    roster_positions?: (string)[] | null;
    scoring_settings: ScoringSettings;
    season: string;
    season_type: string;
    settings: Settings;
    shard: number;
    sport: string;
    status: string;
    total_rosters: number;
}

export interface Settings {
    bench_lock: number;
    best_ball: number;
    capacity_override: number;
    daily_waivers: number;
    daily_waivers_days: number;
    daily_waivers_hour: number;
    daily_waivers_last_ran: number;
    disable_adds: number;
    disable_trades: number;
    divisions?: number | null;
    draft_rounds: number;
    last_report: number;
    last_scored_leg: number;
    league_average_match: number;
    leg: number;
    max_keepers: number;
    num_teams: number;
    offseason_adds: number;
    pick_trading: number;
    playoff_round_type: number;
    playoff_seed_type: number;
    playoff_teams: number;
    playoff_type: number;
    playoff_week_start: number;
    reserve_allow_cov: number;
    reserve_allow_dnr: number;
    reserve_allow_doubtful: number;
    reserve_allow_na: number;
    reserve_allow_out: number;
    reserve_allow_sus: number;
    reserve_slots: number;
    start_week: number;
    taxi_allow_vets: number;
    taxi_deadline: number;
    taxi_slots: number;
    taxi_years: number;
    trade_deadline: number;
    trade_review_days: number;
    type: number;
    waiver_budget: number;
    waiver_clear_days: number;
    waiver_day_of_week: number;
    waiver_type: number;
}

export interface ScoringSettings {
    pass_2pt: number;
    kr_yd: number;
    pass_int: number;
    fgmiss: number;
    rec_yd: number;
    xpmiss: number;
    fgm_30_39: number;
    blk_kick: number;
    pts_allow_7_13: number;
    bonus_rush_yd_100: number;
    ff: number;
    fgm_20_29: number;
    fgm_40_49: number;
    pts_allow_1_6: number;
    st_fum_rec: number;
    def_st_ff: number;
    st_ff: number;
    rush_40p?: number | null;
    pass_td_40p: number;
    pts_allow_28_34: number;
    fgm_50p: number;
    fum_rec: number;
    bonus_rec_yd_200: number;
    def_td: number;
    fgm_0_19: number;
    bonus_pass_yd_300: number;
    pr_td: number;
    int: number;
    pts_allow_0: number;
    bonus_rush_yd_200: number;
    pts_allow_21_27: number;
    rec_2pt: number;
    rec: number;
    pass_cmp_40p?: number | null;
    xpm: number;
    st_td: number;
    kr_td: number;
    def_st_fum_rec: number;
    def_st_td: number;
    sack: number;
    fum_rec_td: number;
    rush_2pt: number;
    rec_td: number;
    rush_td_40p: number;
    rec_td_40p: number;
    pts_allow_35p: number;
    pts_allow_14_20: number;
    rush_yd: number;
    pr_yd: number;
    bonus_pass_yd_400: number;
    rec_40p?: number | null;
    pass_yd: number;
    pass_td: number;
    rush_td: number;
    bonus_rec_yd_100: number;
    fum_lost: number;
    fum: number;
    safe: number;
    def_pr_yd?: number | null;
    yds_allow_400_449?: number | null;
    yds_allow_550p?: number | null;
    yds_allow_100_199?: number | null;
    def_pr_td?: number | null;
    yds_allow_450_499?: number | null;
    def_kr_yd?: number | null;
    yds_allow_500_549?: number | null;
    yds_allow_0_100?: number | null;
    yds_allow_350_399?: number | null;
    def_kr_td?: number | null;
    yds_allow_200_299?: number | null;
}
